extension/src/extension.ts
=> fix renameing leaveout

extension/package-lock.json, extension/package.json
Signed-off-by: Jinbo Wang <jinbwan@microsoft.com>
=> bump version to 0.1.0

extension/src/extension.ts
=> add timeout to walkaround debug issue of mac

extension/src/extension.ts
=> bi might record wrong event status

com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/internal/ProjectUtils.java
=> fix project parse failure

extension/src/commands.ts, extension/src/extension.ts, extension/src/testReportProvider.ts, extension/tslint.json
no need to save/not save test report any more.
=> use contentprovider API to load readonly test report

.travis.yml, extension/.gitignore, extension/src/classPathManager.ts, extension/src/commands.ts, extension/src/configs.ts, extension/src/constants.ts, extension/src/extension.ts, extension/src/junitCodeLensProvider.ts, extension/src/logger.ts, extension/src/protocols.ts, extension/src/testReportProvider.ts, extension/src/testResourceManager.ts, extension/src/testResultAnalyzer.ts, extension/test/extension.test.ts, extension/test/index.ts, extension/tslint.json
=> make tslint strict

extension/package-lock.json, extension/package.json, extension/src/extension.ts, extension/src/testReportProvider.ts, extension/src/testResultAnalyzer.ts
=> format report I: add template engine

extension/resources/templates/report_class.liquid, extension/resources/templates/report_error.liquid, extension/resources/templates/report_failed_method_table.liquid, extension/resources/templates/report_method.liquid, extension/resources/templates/report_method_table.liquid, extension/resources/templates/report_passed_method_table.liquid, extension/src/testReportProvider.ts
=> use template files to render

com.microsoft.java.test.plugin/plugin.xml, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/internal/JUnitTestFetcher.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/internal/JUnitTestSearcher.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/internal/TestDelegateCommandHandler.java
=> [bundle side]support test explorer

com.microsoft.java.test.plugin/pom.xml, com.microsoft.java.test.runner/pom.xml, extension/package.json, pom.xml
=> bump version to 0.2.0

CHANGELOG.md, extension/CHANGELOG.md
=> add changelog

com.microsoft.java.test.plugin/META-INF/MANIFEST.MF
=> fix version upgrade: update osgi bundle version

extension/README.md
=> update readme for telemetry

extension/resources/templates/report_class.pug, extension/resources/templates/report_error.pug, extension/resources/templates/report_method.pug, extension/resources/templates/report_method_table.pug, extension/src/extension.ts, extension/src/testReportProvider.ts
=> test report: refine style

extension/.gitignore, extension/gulpfile.js, extension/package-lock.json, extension/package.json, extension/resources/templates/report_class.pug, extension/resources/templates/report_error.pug, extension/resources/templates/report_method.pug, extension/resources/templates/scss/dark.scss, extension/resources/templates/scss/light.scss
=> report support theme dark/light

extension/src/extension.ts, extension/src/testStatusBarProvider.ts, extension/src/testStatusBarSingleton.ts
=> add test status bar

extension/CHANGELOG.md, extension/README.md
=> update changelog for 0.2.0

extension/resources/templates/report.pug, extension/src/testReportProvider.ts
=> fix class level report bug

com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/internal/JUnitUtility.java
=> walkaround for jdt bug: getAnnotaion would return non-existed annotation

extension/src/Utils/classPathUtility.ts
=> extract classpathutility

extension/src/Runner/jarFileTestRunner.ts, extension/src/Runner/jarTestRunnerResultAnalyzer.ts, extension/src/Runner/testRunnerParameters.ts
=> add jar file test runner

extension/package-lock.json, extension/package.json, extension/src/Constants/constants.ts, extension/src/extension.ts
=> update telemetry wrapper version

extension/resources/templates/report.pug, extension/resources/templates/report_method_table.pug
currently the hover text is href link, it is not user friendly
=> test report: replace original hover text with user friendly ones

extension/src/Runner/JUnitTestRunner/junitRunnerResultAnalyzer.ts
=> add error handling for junit runner result analyzer

extension/src/testStatusBarProvider.ts
=> fix bug 83: correct color on status bar item

extension/package.json, extension/src/extension.ts
=> add setting to configure the position of the test report

com.microsoft.java.test.plugin/META-INF/MANIFEST.MF, com.microsoft.java.test.plugin/pom.xml, com.microsoft.java.test.runner/pom.xml, extension/package.json, pom.xml
=> bump version to 0.3.0

extension/src/Explorer/testExplorer.ts
=> vscode doesn't allow treeitem to be empty

extension/src/Explorer/testExplorer.ts
original fix would affect running tests as we construct test's fullname from name
=> keep on fixing #123: change the name to friendly name at last step to avoid affecting running tests

extension/src/Runner/JUnitTestRunner/junitRunnerResultAnalyzer.ts, extension/src/Runner/testRunnerWrapper.ts
=> fix regression #127

extension/src/extension.ts, extension/src/testStatusBarProvider.ts
=> add more logs

com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/internal/JUnitUtility.java
=> fix null reference exception

extension/src/Constants/commands.ts, extension/src/Explorer/testExplorer.ts, extension/src/Explorer/testTreeNode.ts, extension/src/Runner/JUnitTestRunner/junit5RunnerResultAnalyzer.ts, extension/src/Runner/JUnitTestRunner/junit5TestRunner.ts, extension/src/Runner/JUnitTestRunner/junitRunnerResultAnalyzer.ts, extension/src/Runner/JUnitTestRunner/junitTestRunner.ts, extension/src/Runner/JarFileRunner/jarFileRunnerParameters.ts, extension/src/Runner/JarFileRunner/jarFileRunnerResultAnalyzer.ts, extension/src/Runner/JarFileRunner/jarFileTestRunner.ts, extension/src/Runner/testModel.ts, extension/src/Runner/testRunner.ts, extension/src/Runner/testRunnerParameters.ts, extension/src/Runner/testRunnerWrapper.ts, extension/src/Utils/Logger/logger.ts, extension/src/Utils/Logger/outputTransport.ts, extension/src/Utils/Logger/telemetryTransport.ts, extension/src/Utils/classPathUtility.ts, extension/src/Utils/fetchTestUtility.ts, extension/src/extension.ts, extension/src/junitCodeLensProvider.ts, extension/src/testReportProvider.ts, extension/src/testStatusBarProvider.ts, extension/test/extension.test.ts, extension/tslint.json
=> fix bug: data sent to stdout might be cut off

com.microsoft.java.test.plugin/plugin.xml, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/internal/ProjectInfo.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/internal/ProjectInfoFetcher.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/internal/TestDelegateCommandHandler.java
=> configI: add command to fetch project info

.gitignore, extension/src/Constants/commands.ts, extension/src/Constants/configs.ts
=> configII: add commands

extension/src/projectManager.ts
=> configIII: add project manager

extension/src/Models/testConfig.ts, extension/src/testConfigManager.ts
=> configIV: add test config manager

extension/src/Explorer/testExplorer.ts, extension/src/Runner/JarFileRunner/jarFileTestRunner.ts, extension/src/Runner/testRunner.ts, extension/src/Runner/testRunnerWrapper.ts, extension/src/extension.ts
=> add commands

extension/package.json, extension/src/Runner/JUnitTestRunner/junit5TestRunner.ts, extension/src/Runner/JUnitTestRunner/junitTestRunner.ts, extension/src/Runner/JarFileRunner/jarFileTestRunner.ts, extension/src/Runner/testRunnerParameters.ts, extension/src/Runner/testRunnerWrapper.ts, extension/src/Utils/Logger/outputTransport.ts, extension/src/junitCodeLensProvider.ts
=> add logic for config

extension/src/testConfigManager.ts
=> fix bug #155

extension/src/Constants/configs.ts, extension/src/extension.ts, extension/src/testConfigManager.ts
=> change test config storage path from extension folder to storage folder

extension/package.json, extension/src/Constants/commands.ts, extension/src/Explorer/testExplorer.ts, extension/src/Utils/Logger/outputTransport.ts, extension/src/extension.ts, extension/src/testStatusBarProvider.ts
=> add cancel test command into menu when user clicks status bar

extension/package-lock.json, extension/package.json, extension/src/Explorer/testExplorer.ts, extension/src/Runner/JarFileRunner/jarFileTestRunner.ts, extension/src/Runner/testRunner.ts, extension/src/Runner/testRunnerWrapper.ts
=> add implementation for cancelling a test run

extension/src/extension.ts
=> to fix #165: remove duplicate error message

extension/src/Constants/commands.ts, extension/src/Utils/Logger/outputTransport.ts, extension/src/extension.ts, extension/src/junitCodeLensProvider.ts
=> remove 'run with config'  from codelens

extension/package.json, extension/src/testStatusBarProvider.ts
=> use new progress UI

extension/launch.test.schema.json, extension/package.json, extension/src/Constants/configs.ts, extension/test.launch.schema.json
=> add json schema validation for test.launch.json

.travis.yml
=> fix travis failure for node10

extension/CHANGELOG.md
=> update changelog for 0.6.0

com.microsoft.java.test.plugin/META-INF/MANIFEST.MF, com.microsoft.java.test.plugin/pom.xml, com.microsoft.java.test.runner.junit5/pom.xml, com.microsoft.java.test.runner/pom.xml, extension/README.md, extension/package.json, pom.xml
Signed-off-by: zhouxuan <lilyzhou0624@hotmail.com>
=> bump to 0.6.0

extension/src/Runner/JUnitTestRunner/junit5RunnerResultAnalyzer.ts, extension/src/Runner/JUnitTestRunner/junitRunnerResultAnalyzer.ts, extension/src/Runner/JarFileRunner/jarFileRunnerResultAnalyzer.ts, extension/src/Runner/JarFileRunner/jarFileTestRunner.ts
=> fixbug: when cancelling a test run, it's hard to tell whether a test is skipped or cancelled

extension/src/Runner/testRunnerWrapper.ts
=> fix cancel test bug: prelaunch task cannot be cancelled

extension/src/Explorer/testExplorer.ts, extension/src/extension.ts
=> fix bug: run with config from test explorer doesn't work

extension/src/Runner/JarFileRunner/jarFileTestRunner.ts, extension/src/Runner/testRunnerWrapper.ts, extension/src/Utils/classPathUtility.ts, extension/src/projectManager.ts
=> for compliance, not send user info to telemetry

extension/src/testConfigManager.ts
=> one more place to remove user info

extension/package.json
=> bump version to 0.6.1

extension/package.json
Hi,
I am developer from VS Code and recently we added a new test view container. Refer to the release notes [here](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_23.md#contributions-to-the-activity-bar). 
I am going through the popular extensions in the market place those contribute test related custom views and moving those view to Test view container.
I would request to accept this PR and publish the extension with changes.
Thanks
=> Move test explorer to Test view container

pom.xml
see https://gitter.im/redhat-developer/vscode-java?at=5ad8f68c6bbe1d2739048e48
=> fix build break

extension/package-lock.json, extension/src/extension.ts, extension/src/testReportProvider.ts
https://github.com/Microsoft/vscode-java-test/issues/206
=> enhancement:auto-refresh test report when test file updates

extension/src/Models/testConfig.ts, extension/src/Runner/JarFileRunner/jarFileTestRunner.ts, extension/src/testConfigManager.ts
=> support environment variables for test configuration

extension/src/Runner/JarFileRunner/jarFileTestRunner.ts
=> update test config env: should be set in env

com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/internal/JUnitPlugin.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/internal/JavaModelEventProvider.java, extension/package-lock.json, extension/src/Constants/commands.ts, extension/src/extension.ts
to resolve #205 #198 
Currently there is no event fired when language server updates the project, so I have to add a timeout, which is 10 seconds
=> update classpath when user updates pom.xml or build.gradle

com.microsoft.java.test.plugin/META-INF/MANIFEST.MF, com.microsoft.java.test.plugin/pom.xml, com.microsoft.java.test.runner.junit5/pom.xml, com.microsoft.java.test.runner/pom.xml, extension/CHANGELOG.md, extension/README.md, extension/package.json, pom.xml
=> bump version to 0.7.0 and update changelog

extension/src/Runner/JarFileRunner/jarFileTestRunner.ts
=> not lose default process.env

extension/launch.test.schema.json
provide launch.test.json schema description for #215
=> added env variables to launch.test.schema.json

com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/JUnitLauncher.java
some spring boot tests would hang as context isn't closed and thus the process is not terminated.
#101
=> fix test hang issue

com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/JUnitLauncher.java
=> flush streams before exit

com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/TestRunnerUtil.java
This is for troubleshooting `No test found to run` issue.
=> add detailed failure reason for parsing test issue.

extension/src/Runner/JUnitTestRunner/junitRunnerResultAnalyzer.ts
=> fix bug: failed to analyze runner output data.

extension/src/Runner/JarFileRunner/jarFileTestRunner.ts, extension/src/extension.ts, extension/src/projectManager.ts, extension/src/testConfigManager.ts
=> fix bug for default working directory: should point to the project folder rather than the workspace folder

extension/src/classPathManager.ts, extension/src/extension.ts, extension/src/projectManager.ts
=> fix classpath issue for multiple projects in a workspace folder

extension/package.json
see whether this could help resolve `java.lang.NoClassDefFoundError`
=> expose the command to manually refresh classpath

extension/src/extension.ts
=> fix bug: not await promise

com.microsoft.java.test.plugin/META-INF/MANIFEST.MF, com.microsoft.java.test.plugin/pom.xml, com.microsoft.java.test.runner.junit5/pom.xml, com.microsoft.java.test.runner/pom.xml, extension/CHANGELOG.md, extension/package.json, pom.xml
=> bump to 0.7.1 and update changelog

com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/internal/JUnitTestFetcher.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/internal/JUnitTestSearcher.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/internal/testsuit/TestSuite.java, extension/src/Models/protocols.ts
fully qualified name of a test method isn't enough for the scenario that multi-projects are in a workspace folder
=> add project name into test suite

extension/src/Runner/testRunnerWrapper.ts
=> fix regression: test is not detected

extension/src/testConfigManager.ts
=> update write file method

extension/src/classPathManager.ts, extension/src/projectManager.ts
=> update map key from Uri to string to avoid duplicate items

extension/src/projectManager.ts
=> try to fix project parse error

extension/src/classPathManager.ts, extension/src/projectManager.ts, extension/src/testConfigManager.ts
=> fix bug according to bi

extension/src/Runner/JUnitTestRunner/junit5RunnerResultAnalyzer.ts, extension/src/Runner/JUnitTestRunner/junitRunnerResultAnalyzer.ts, extension/src/Runner/JarFileRunner/jarFileRunnerResultAnalyzer.ts, extension/src/Runner/JarFileRunner/jarFileTestRunner.ts
=> rewrite the logic to consume the output

extension/src/Runner/JUnitTestRunner/junit5TestRunner.ts, extension/src/Runner/JUnitTestRunner/junitTestRunner.ts, extension/src/Runner/JarFileRunner/jarFileTestRunner.ts
the latter one need to specify maxbuffersize option and it is hard to predict a good value for all cases.
=> Use spawn instead of exec to start runner

extension/src/Runner/JarFileRunner/jarFileTestRunner.ts, extension/src/Utils/Logger/logger.ts, extension/src/extension.ts, extension/src/junitCodeLensProvider.ts, extension/src/testConfigManager.ts
=> add usertag to tell system error and user error

com.microsoft.java.test.plugin/META-INF/MANIFEST.MF, com.microsoft.java.test.plugin/pom.xml, com.microsoft.java.test.runner.junit5/pom.xml, com.microsoft.java.test.runner/pom.xml, extension/CHANGELOG.md, extension/package.json, pom.xml
=> Bump version to 0.8.0 and update changelog

extension/src/projectManager.ts
=> Update error message

extension/gulpfile.js, extension/package.json
=> update the gulp script to download the language server automatically

extension/src/classPathManager.ts, extension/src/projectManager.ts
... to make sure the execution is synchronized.
=> Wrap the asynchronized calls in .map() through Promise.all()

extension/package.json, extension/src/extension.ts
=> Always show the explorer after the extension is activated

extension/package.json
=> Add missing commands into the activation events

extension/src/Runner/testRunnerWrapper.ts, extension/src/extension.ts, extension/src/testStatusBarProvider.ts
=> Using export to make the status bar a singleton

extension/src/testStatusBarProvider.ts
…since it implements dispose()
=> Add Disposable interface for the TestStatusBar declaration 

extension/src/testStatusBarProvider.ts
=> Keep the progress moving when running tests

com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/internal/JavaModelEventProvider.java, extension/CHANGELOG.md, extension/package.json
=> Fix the bug that runner will interfere with Java LS

com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/ClassSearcher.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/MethodSearcher.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/NestedClassSearcher.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/PackageSearcher.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/TestItemSearcher.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java
To address the comments in this PR: https://github.com/Microsoft/vscode-java-test/pull/315
=> Update code according to comments

extension/package.json, extension/src/constants/commands.ts, extension/src/explorer/TestTreeNode.ts, extension/src/explorer/testExplorer.ts, extension/src/extension.ts, extension/src/protocols.ts, extension/src/utils/commandUtils.ts, extension/src/utils/protocolUtils.ts
Add the codes to show the explorer
=> Can show the explorer

extension/src/explorer/explorerNodeManager.ts, extension/src/explorer/testExplorer.ts, extension/src/extension.ts
=> Add file watcher to refresh the explorer

com.microsoft.java.test.plugin/plugin.xml, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/handler/TestDelegateCommandHandler.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/JUnit4TestSearcher.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/JUnit5TestSearcher.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/MethodSearcher.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/PackageSearcher.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/TestFrameworkSearcher.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/JUnitUtility.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/ProjectUtils.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java
=> Add code for searching the code lenses - Java

com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/common/ITestLauncher.java, com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/common/MessageUtils.java, com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/common/Pair.java, com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/common/TestMessageConstants.java, com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/common/TestMessageItem.java, com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/common/TestMessageType.java, com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/common/TestOutputStream.java, com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/common/TestRunnerMessageHelper.java, com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/common/TestStream.java
This is the preparation work to abstract each runner.
=> Add the common logic for the runners

com.microsoft.java.test.runner/pom.xml, com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/testng/TestNGLauncher.java, com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/testng/TestNGListener.java, com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/testng/TestNGRunner.java
=> Add TestNG support - Java part

extension/src/codeLensProvider.ts
Add view test report entry in code lens provider
=> Add view test report entry in code lens provider

com.microsoft.java.test.plugin/plugin.xml, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/handler/TestDelegateCommandHandler.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/model/TestItem.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/model/TestLevel.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/BaseFrameworkSearcher.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/JUnit4TestSearcher.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/JUnit5TestSearcher.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/TestFrameworkSearcher.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/TestNGTestSearcher.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java
Can search all test items under a certain node - Java part
=> Can search all test items under a certain node

extension/src/explorer/testExplorer.ts
=> Sort the nodes in explorer

extension/src/utils/cpUtils.ts
=> Swallow the error when killing the child process

extension/src/commands/explorerCommands.ts
=> Fix the wrongly used API: Progress.report()

extension/src/extension.ts, extension/src/runners/runnerExecutor.ts, extension/src/testStatusBarProvider.ts
=> Hide the status bar if no test items need to be tested

com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/ProjectUtils.java
=> Fix the bug that cannot get right test scope for Gradle project

extension/src/runners/runnerExecutor.ts
`!test.kind` will return true if the value of kind is `0`.
=> Check the kind is undefined or not

com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java
=> Fix the bug that cannot run method test from explorer

com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/RuntimeClassPathUtils.java
=> Get the Java project directly instead of using the IProject when resolving the class path

com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java
=> Fix the bug that running test method from explorer will run the entire test in the class

extension/src/runners/junit5Runner/JUnit5RunnerResultAnalyzer.ts
=> Fix the "Cannot read property 'indexOf' of undefined" bug when running JUnit 5 tests

extension/resources/templates/report.pug, extension/resources/templates/scss/dark.scss, extension/src/testReportProvider.ts
=> Render the report in one time instead of open a new web page when switching the report type

extension/src/testStatusBarProvider.ts
=> Using default color for the status bar

src/codeLensProvider.ts
=> Change the skip icon to make it responsive to different themes

resources/templates/report.pug, resources/templates/report_method_table.pug
Address the issue: #314 
Here are the screenshots for different scenarios:
=> Make the final result of the test report more clearly

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/BaseFrameworkSearcher.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/JUnit4TestSearcher.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/JUnit5TestSearcher.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/TestFrameworkSearcher.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/TestNGTestSearcher.java, src/runners/junit5Runner/JUnit5RunnerResultAnalyzer.ts
=> Add support for JUnit 5's @ParameterizedTest

src/explorer/testExplorer.ts
=> Sort the tree node using display name instead of full name

java-extension/com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/Launcher.java
=> Fix the bug that runner won't stop

src/testReportProvider.ts
=> Fix the bug that test report will not get focus

resources/templates/report.pug
=> Change the style of the report to become fluidly

resources/templates/report_method_table.pug
=> Refine the report page

src/extension.ts, src/logger/logger.ts
=> fix the bug that could not find log files

src/testReportProvider.ts
=> Pass the position argument into the reveal()

resources/templates/report.pug, resources/templates/report_method_table.pug, resources/templates/scss/report.scss, src/testReportProvider.ts
Address #517 - Add hover style
Updated:
=> Change the row background color when hovering

resources/templates/report_method_table.pug, resources/templates/scss/report.scss
=> Refine the class name row in the report

package.json
=> Activate the extension when workspace contains pom.xml/build.gradle

resources/templates/report.pug, resources/templates/report_method_table.pug, resources/templates/scss/report.scss
=> Add arrow before the collapse

package.json, package.nls.json, package.nls.zh.json
=> Support Chinese Locale for package.json

.vscodeignore, README.md
The `vsce` will parse the `demo/demo.gif` to HTTP link
=> Ignore the gif to shrink the *.vsix size

java-extension/com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/junit4/JUnit4RunnerUtil.java
=> Fix the bug that test will be skipped if the class only contains one methods in JUnit 4

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java
=> Fix bug that failed to parse the Java project

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/model/TestItem.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/BaseFrameworkSearcher.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/JUnit5TestSearcher.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/TestFrameworkSearcher.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestFrameworkUtils.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestItemUtils.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java, src/protocols.ts, src/runners/junit5Runner/JUnit5Runner.ts
=> Add parameter information for JUnit 5 test methods

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java
=> Fix the bug that run tests from workspace folder will run all the tests in the workspace

java-extension/com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/testng/TestNGLauncher.java
=> [Bug Fix] Cannot run inner class test in TestNG

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java
=> [Bug Fix] Run inner class tests will also run the tests of the parent class

.gitignore, .vscodeignore, gulpfile.js, package.json, resources/templates/report.pug, src/testReportProvider.ts
=> Pack the report resources and load them locally

src/logger/outputChannelTransport.ts, src/runners/baseRunner/BaseRunnerResultAnalyzer.ts
=> Unescape the json string to get better format

CHANGELOG.md, README.md, package.json, package.nls.json, package.nls.zh.json, src/constants/configs.ts, src/extension.ts, src/logger/logger.ts, src/logger/outputChannelTransport.ts, src/runners/baseRunner/BaseRunnerResultAnalyzer.ts, src/testReportProvider.ts, src/utils/settingUtils.ts, src/utils/testReportUtils.ts
=> Add the log level setting

src/commands/executeTests.ts, src/testConfigManager.ts
The first part of the work #524
=> Stop creating launch.test.json when run/debug the tests

package.json, package.nls.json, package.nls.zh.json, src/commands/executeTests.ts, src/commands/explorerCommands.ts, src/runners/baseRunner/BaseRunner.ts, src/runners/runnerExecutor.ts, src/testConfigManager.ts, src/utils/configUtils.ts
=>  Implement the logic to adopt new configuration schema when it's provided

package-lock.json, package.json, package.nls.json, package.nls.zh.json, src/constants/configs.ts, src/testConfigManager.ts
=> Hint the user when the deprecated configuration is used

package.json, resources/templates/report.pug, resources/templates/report_method_table.pug, resources/templates/scss/report.scss, src/commands/explorerCommands.ts, src/constants/commands.ts, src/explorer/testExplorer.ts, src/extension.ts, src/protocols.ts, src/runners/baseRunner/BaseRunnerResultAnalyzer.ts, src/testReportProvider.ts, src/testResultManager.ts
=> Can navigate to the method from report

src/commands/executeTests.ts, src/runners/runnerExecutor.ts
=> Fix the bug that test cannot be canceled

src/codeLensProvider.ts, src/testReportProvider.ts, src/testResultManager.ts
=> Fix the bug that status icon is not right in the inner test class

src/runners/baseRunner/BaseRunner.ts, src/runners/junit4Runner/Junit4Runner.ts, src/runners/junit5Runner/JUnit5Runner.ts, src/runners/testngRunner/TestNGRunner.ts
=> Adjust the order of params passed to the runner

.vscodeignore, CONTRIBUTING.md, README.md
=> Add CONTRIBUTING.md

src/runners/baseRunner/BaseRunner.ts, src/runners/runnerExecutor.ts, src/utils/settingUtils.ts
=> Support ${workspaceFolder} expansion in all the fields in the test configurations

CHANGELOG.md, src/utils/settingUtils.ts
=> [bugfix] missing normal values in the test configurations

package-lock.json, package.json
=> Update vscode-extension-telemetry-wrapper version to 0.3.9

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/JUnit4TestSearcher.java
=> Support JUnit 4 Theory annotation

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/JUnit5TestSearcher.java
=> Support Junit 5 RepeatedTest

java-extension/com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/junit4/JUnit4RunnerUtil.java, java-extension/com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/testng/TestNGLauncher.java
=> Do not initialize the class when reflecting

src/codeLensProvider.ts
=> regression: status icon in Code Lens is wrong

src/runners/baseRunner/BaseRunner.ts
=> Fix the encoding issue

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestFrameworkUtils.java
=> [Bugfix] Recognize the test cases with start import

src/testReportProvider.ts
The listener `onDidReceiveMessage()` will be registered again and again when the `report()` method is called.
Only register the listener once when `this.panel === null`. Also, put it into the subscription since it is a `Disposable`
=> [bugfix] Register the listener only once when creating the webview

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/RuntimeClassPathUtils.java
=> Can resolve the classpath of the invisible project

CHANGELOG.md, java-extension/build-tools/pom.xml, java-extension/com.microsoft.java.test.plugin/META-INF/MANIFEST.MF, java-extension/com.microsoft.java.test.plugin/pom.xml, java-extension/com.microsoft.java.test.runner/pom.xml, java-extension/pom.xml, package-lock.json, package.json
Will update the date when it's totally ready...
=> Prepare the 0.16.0

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/ProjectTestUtils.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/RuntimeClassPathUtils.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestItemUtils.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java, src/testResultManager.ts
=> fix: Support default package

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/ProjectTestUtils.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/RuntimeClassPathUtils.java
=> fix: Parse the project in path correctly

CHANGELOG.md, java-extension/build-tools/pom.xml, java-extension/com.microsoft.java.test.plugin/META-INF/MANIFEST.MF, java-extension/com.microsoft.java.test.plugin/pom.xml, java-extension/com.microsoft.java.test.runner/pom.xml, java-extension/pom.xml, package-lock.json, package.json
=> chore: Prepare for 0.17.0

java-extension/com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/Launcher.java, src/constants/dialogOptions.ts, src/runners/baseRunner/BaseRunnerResultAnalyzer.ts, src/runners/runnerExecutor.ts
Fix #537 
The extension won't show anything when exception happens
Give the user a hint
=> fix: print the unexpected exceptions to the output channel

package.json, package.nls.json, package.nls.zh.json, src/constants/configs.ts, src/runners/runnerExecutor.ts, src/utils/settingUtils.ts
=> feat: Automatically show test report after execution

src/runners/baseRunner/BaseRunnerResultAnalyzer.ts
=> fix: Correct the log level for the error messages

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/JUnit4TestSearcher.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/JUnit5TestSearcher.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java, src/runners/junit5Runner/JUnit5RunnerResultAnalyzer.ts
=> feat: Add @nested support for JUnit 5

resources/templates/report_method_table.pug, resources/templates/scss/report.scss
=> fix: Wrong collapsed icon in test report

README.md, package.json, package.nls.json, package.nls.zh.json, src/codelens/TestCodeLensController.ts, src/codelens/TestCodeLensProvider.ts, src/constants/configs.ts, src/extension.ts, src/runners/runnerExecutor.ts
=> feat: Add a way to customize the visibility of 'run' and 'debug' Code Lens

src/runners/baseRunner/BaseRunner.ts
=> feat: Print the command to the output with verbose level

java-extension/com.microsoft.java.test.plugin/META-INF/MANIFEST.MF, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/RuntimeClassPathUtils.java
=> fix: Use launch configuration to resolve the classpath

README.md
The follow-up of https://github.com/microsoft/vscode-java-test/issues/470#issuecomment-510947992
=> docs: Add FAQ in the README.md

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/JUnit5TestSearcher.java
=> feat: Support JUnit 5 TestTemplate

README.md, package.json, package.nls.json, package.nls.zh.json, src/constants/commands.ts, src/constants/configs.ts, src/runners/runnerExecutor.ts, src/utils/settingUtils.ts
=> feat: Add 'java.test.forceBuildBeforeLaunchTest' Setting

package.json, package.nls.json, package.nls.zh.json, src/constants/configs.ts, src/runners/runnerExecutor.ts, src/utils/settingUtils.ts
=> feat: Support auto save the dirty files before launching the test

java-extension/com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/Launcher.java, java-extension/com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/common/TestOutputStream.java, java-extension/com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/common/TestStream.java, src/constants/configs.ts, src/logger/outputChannelTransport.ts, src/runners/ITestRunner.ts, src/runners/baseRunner/BaseRunner.ts, src/runners/baseRunner/BaseRunnerResultAnalyzer.ts, src/runners/junit4Runner/JUnit4RunnerResultAnalyzer.ts, src/runners/junit5Runner/JUnit5RunnerResultAnalyzer.ts, src/runners/models.ts, src/runners/runnerExecutor.ts, src/runners/testngRunner/TestNGRunnerResultAnalyzer.ts
=>  fix: Use socket to deliver test result

.vscode/launch.json, java-extension/com.microsoft.java.test.plugin/META-INF/MANIFEST.MF, java-extension/com.microsoft.java.test.plugin/build.properties, java-extension/com.microsoft.java.test.plugin/pom.xml, java-extension/com.microsoft.java.test.plugin/target.target
- Update launch.json
- Add apache.common.lang3
- Update target platform
=> chore: Update the build pipelines

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/launchers/JUnitLaunchUtils.java, src/runners/baseRunner/BaseRunner.ts, src/utils/commandUtils.ts, src/utils/launchUtils.ts
=> fix: Cannot run JUnit4 test from workspace root

src/runners/runnerScheduler.ts
=> fix: terminate the execution when canceling

src/runners/baseRunner/BaseRunnerResultAnalyzer.ts
=> Fix the bug that cannot show error log when level is info/verbose

src/runners/runnerScheduler.ts
=> fix: Do not reuse the launch configuration for each test task

src/runners/junit4Runner/Junit4Runner.ts, src/utils/configUtils.ts, src/utils/launchUtils.ts
=> fix: Disconnect the debug session when cleaning up

src/runners/junitRunner/JunitRunner.ts
=> fix: Add arguments when sending custom request to debug session

src/utils/launchUtils.ts
=> fix: Replace the port number instead of appending a new one

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/launchers/JUnitLaunchConfigurationDelegate.java
fix #807 
This fix also depends on https://github.com/microsoft/java-debug/pull/304 to get released
=> feat: Support modular test JUnit projects

src/extension.ts
=> Support 'CollapseAll' in Test Explorer

src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts
=> Fix the bug that cannot parse the assumption failure

src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts
=> Regression: Cannot correctly parse the JUnit 5 ParameterizedTest result

package-lock.json, package.json, src/codelens/TestCodeLensProvider.ts, src/utils/platformUtils.ts
=> Migrate the Code Lens status icon to Octicons

src/runners/baseRunner/BaseRunner.ts, src/runners/junitRunner/JunitRunner.ts, src/utils/launchUtils.ts
fix: https://github.com/testforstephen/vscode-pde/issues/12
=> fix: Append the port args when it's not set

resources/templates/report_method_table.pug, src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts, src/runners/models.ts, src/runners/testngRunner/TestNGRunnerResultAnalyzer.ts, test/01.codelens.test.ts
=> fix: Regression bug that cannot show execution time of the tests

src/commands/explorerCommands.ts, src/runners/ITestRunner.ts, src/runners/baseRunner/BaseRunner.ts, src/runners/junitRunner/JunitRunner.ts, src/runners/models.ts, src/runners/runnerScheduler.ts, src/runners/testngRunner/TestNGRunner.ts
=> bugfix: Cannot run all tests for TestNG

src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts, test/maven-junit4-suite/codelens.test.ts, test/shared.ts, test/test-projects/junit4/src/test/java/junit4/ExceptionInBefore.java
=> Handle the '%ERROR' output from the runner

src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts, test/maven-junit4-suite/codelens.test.ts, test/shared.ts, test/test-projects/junit4/src/test/java/junit4/ParameterizedTest.java
=> bugfix: Parse the JUnit4's parameterized tests correctly

resources/templates/report.pug, resources/templates/scss/report.scss
=> fix: Rotate the arrow icon when expand/collapse the test report

resources/templates/report.pug, resources/templates/report_method_table.pug, src/testReportProvider.ts
=> Add skipped tab in test report

java-extension/pom.xml, package.json
=> Update junit runtime version

.vscode/extensions.json, CONTRIBUTING.md
Add more content per discussion here: https://github.com/microsoft/vscode-java-test/issues/975#issuecomment-614451991
=> Add more content to the contribution guide

package.json, package.nls.json, package.nls.zh.json, src/runConfigs.ts, src/utils/launchUtils.ts
=> Add test config field to specify source paths.

src/testStatusBarProvider.ts
Since now the status bar can accept a `Command` object
=> Remove the workaround to trigger command from status bar

src/testReportProvider.ts
=> Migrate to asWebviewUri() API

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java, src/codelens/TestCodeLensProvider.ts, test/gradle-junit5-suite/codelens.test.ts, test/shared.ts, test/test-projects/junit5/src/test/java/junit5/NestedTest.java
=> bugfix: Can run nested cases

src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts, test/gradle-junit5-suite/codelens.test.ts, test/shared.ts, test/test-projects/junit5/build.gradle, test/test-projects/junit5/src/test/java/junit5/cucumber/CucumberSteps.java, test/test-projects/junit5/src/test/java/junit5/cucumber/CucumberTest.java, test/test-projects/junit5/src/test/resources/Test.feature
=> bugfix: Can update the test result for cucumber tests

src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts, test/gradle-junit5-suite/codelens.test.ts, test/test-projects/junit5/src/test/java/junit5/ParameterizedAnnotationTest.java
=> bugfix: wrong test result for parameterized tests

extension.bundle.ts, package.json, package.nls.json, package.nls.zh.json, src/extension.ts, src/runners/runnerScheduler.ts, src/testReportProvider.ts, src/testStatusBarProvider.ts, test/maven-junit4-suite/codelens.test.ts
=> feat: Support show test report through keyboard shortcut and command palette

src/testFileWatcher.ts
`*.JAVA` is not a valid extension name (can not use javac to compile). So remove it.
=> bugfix: Remove invalid watch pattern

package.json, src/constants/commands.ts, src/explorer/testExplorer.ts, src/extension.ts
Use welcome page when Language server is in Lightweight Mode.
=> Add welcome page for test explorer in LightWeight mode

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/launchers/JUnitLaunchUtils.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestFrameworkUtils.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java, src/commands/explorerCommands.ts, src/testItemModel.ts, src/utils/commandUtils.ts
=> Add the cancellation event check

.travis.yml
=> chore: Stop OSX build temporarily

src/utils/commandUtils.ts
=> bugfix: Ignore error caused by request cancelled

package.json
=> ux: Update the run buttons to make them consistent with debugger

src/extension.ts
Initialize logger ahead of time
Fixed: #1087
=> fix: Initialize logger ahead of time

package-lock.json, package.json, resources/templates/report.pug, resources/templates/report_method_table.pug, src/commands/testReportCommands.ts, src/constants/commands.ts, src/extension.ts, src/testReportProvider.ts, src/utils/commandUtils.ts
=> feat: Navigate from stack trace to source

src/testReportProvider.ts
fix #1097 
Follow-up work in next iteration: #1096
=> fix: Cannot go to test source

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/launchers/JUnitLaunchUtils.java
=> fix: Set working directory for TestNG project

src/commands/testReportCommands.ts, src/constants/commands.ts, src/extension.ts, src/testReportProvider.ts, test/gradle-junit5-suite/codelens.test.ts, test/gradle-junit5-suite/testReport.test.ts, test/gradle-modular-suite/modular.gradle.test.ts, test/maven-junit4-suite/codelens.test.ts
=> refactor: Wrap open test document code as a command

package-lock.json, package.json, src/utils/launchUtils.ts, tsconfig.json
This PR enabled tsconfig for "noImplicitAny" and fixed related errors.
=> refactor: Fix implicit any

package.json, src/constants/configs.ts, src/extension.ts
=> Do not show the Test Explorer when no Java files in workspace

src/runners/baseRunner/BaseRunner.ts
=> fix: Open debug console on session start

package.json
=> feat: Change the scope of 'java.test.report.showAfterExecution' to window

src/runners/runnerScheduler.ts
fix #1122
When the project has mixed test framework used, the progress reporter needs to be renewed for each execution. Otherwise, the debug session cannot be started successfully.
=> fix: Cannot run mixed test framework cases

src/testStatusBarProvider.ts
=> fix: Add label information to the test result status

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/launchers/JUnitLaunchUtils.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java, src/utils/commandUtils.ts
=> fix: Cannot run tests from a package root

package-lock.json, package.json, src/testFileWatcher.ts
Due to this [issue](https://github.com/pugjs/pug-loader/issues/126), have to move pug to dev-dependency to unblock `vsce package`
=> chore: move 'pug' into dev-dependencies

src/testReportProvider.ts
=> fix: Always show last execution result when click show results from code lens

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestGenerationUtils.java
part of #1172 
This PR is to prepare for the next half of the feature: generate tests from source.
=> refactor: Use a metadata class to store the methods information

src/extension.ts, src/provider/codeActionProvider.ts
We will first release this code action in test files.
=> fix: Only show 'generate tests' in test source files

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestGenerationUtils.java, src/provider/codeActionProvider.ts
=> fix: Generated test methods reduced the visibility of the inherited methods

package.json
=> disable extension in virtual workspaces

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/model/Option.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/JUnitPlugin.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestGenerationUtils.java, package-lock.json, package.json, src/commands/generationCommands.ts, src/extension.ts
part of #1172
This is to add the capability to select inherited methods. See:
https://user-images.githubusercontent.com/6193897/117597498-48c51700-b178-11eb-97b2-ef055b08dab5.mp4
=> feat: Support select inherit methods when generating tests

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestGenerationUtils.java
=> fix: Method names are duplicated when overload methods are selected

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestGenerationUtils.java
=> fix: Can generate tests from interface, enum and record

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestGenerationUtils.java
fix #1208
https://user-images.githubusercontent.com/6193897/119313404-15b97200-bca6-11eb-88c2-33702b4bc217.mp4
=> fix: Can select peer project if current project does not contain test framework

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestGenerationUtils.java
=> typo: inherit -> inherited

src/extension.ts, src/provider/codeActionProvider.ts
=> fix: Extension cannot be activated when switching from restrict mode to trust mode

java-extension/com.microsoft.java.test.plugin/plugin.xml, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/handler/TestDelegateCommandHandler.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java
This is to list all the test classes and methods in a file, which will be used to render the editor decorations (the previous code lenses).
=> List test classes & methods in a file

src/controller/utils.ts
When user is updating the test file, he may delete all the test cases. In that case we need to remove the related test items as well. (instead of directly return when no test items is found -- the previous behavior)
fix #1262
=> fix: Remove test items no test items is found due to updating

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestItemUtils.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java
=> fix: Do not show internal name for invisible project

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java, src/controller/testController.ts, src/extension.ts, src/provider/testSourceProvider.ts
=> fix: Better handle the workspace folder change event

src/commands/testExplorerCommands.ts, src/extension.ts
=> fix: The testing decoration disappear after refresh

package.json
the marketplace now have a new category for `Testing`
=> chore: Change extension category to 'Testing'

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/launchers/JUnitLaunchUtils.java
=> fix: Cannot resolve launch argument for TestNG

java-extension/com.microsoft.java.test.plugin/plugin.xml
=> fix: Register 'findTestLocation' command in bundle

src/runners/baseRunner/RunnerResultAnalyzer.ts, src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts, src/runners/testngRunner/TestNGRunnerResultAnalyzer.ts, test/suite/JUnitAnalyzer.test.ts
fix #1266 
If the stacktrace contains location belonging to the source file, then we show it at that location.
https://user-images.githubusercontent.com/6193897/138637985-c0773467-697e-41c9-b127-e242af17ca8e.mp4
=> feat: Show stack trace to where error occurs

package.json, package.nls.json, package.nls.zh.json, src/runConfigs.ts, src/utils/launchUtils.ts, test/suite/config.test.ts
=> feat: Add 'preLaunchTask' to test configuration

src/controller/testController.ts
=> chore: Record the test framework in use

java-extension/com.microsoft.java.test.runner/pom.xml
=> Update gson to 2.8.9

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/ProjectTestUtils.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestNavigationUtils.java, package.json, package.nls.json, package.nls.zh.json, src/commands/navigation/navigationCommands.ts, src/constants.ts, src/extension.ts, test/suite/navigation.test.ts
=> feat: Support 'go to test target'

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestNavigationUtils.java, package.json, package.nls.json, package.nls.zh.json, src/commands/navigation/navigationCommands.ts, src/constants.ts, src/extension.ts, test/suite/navigation.test.ts
=> Rename 'test target' to 'test subject'

CHANGELOG.md
=> chore: Add a new line in change log

java-extension/com.microsoft.java.test.runner/pom.xml, scripts/buildJdtlsExt.js, src/utils/launchUtils.ts
=> chore: Use fat jar for the TestNG runner

package-lock.json, package.json, src/controller/testController.ts, src/runners/baseRunner/RunnerResultAnalyzer.ts, src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts
=> fix: Use <br> to break lines in test message

CHANGELOG.md, java-extension/build-tools/pom.xml, java-extension/com.microsoft.java.test.plugin.site/category.xml, java-extension/com.microsoft.java.test.plugin.site/pom.xml, java-extension/com.microsoft.java.test.plugin/META-INF/MANIFEST.MF, java-extension/com.microsoft.java.test.plugin/pom.xml, java-extension/com.microsoft.java.test.runner/pom.xml, java-extension/pom.xml, package-lock.json, package.json
=> chore: Prepare for 0.33.1

src/utils/commandUtils.ts
=> fix: Extract the error properly

.vscode/launch.json, src/commands/testDependenciesCommands.ts, test/index.ts, test/suite/config.test.ts, test/suite/navigation.test.ts, test/test-projects/simple/.vscode/settings.json, test/test-projects/simple/src/App.java, test/unmanaged-folder-suite/enableTests.test.ts, test/unmanaged-folder-suite/index.ts
=> test: Add tests for enabling tests

CHANGELOG.md, java-extension/build-tools/pom.xml, java-extension/com.microsoft.java.test.plugin.site/category.xml, java-extension/com.microsoft.java.test.plugin.site/pom.xml, java-extension/com.microsoft.java.test.plugin/META-INF/MANIFEST.MF, java-extension/com.microsoft.java.test.plugin/pom.xml, java-extension/com.microsoft.java.test.runner/pom.xml, java-extension/pom.xml, package-lock.json, package.json
=> chore: Prepare for 0.34.0

java-extension/com.microsoft.java.test.plugin/target.target, java-extension/pom.xml
=> chore: Update the target platform

src/extension.ts
- Do the real activstion job when receive the service ready event.
This could make sure JDT.LS have more CPU resources to do the initial
build.
=> perf: Postpone the activation job after the ls is ready

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestGenerationUtils.java, src/commands/testDependenciesCommands.ts
=> feat: Enabling tests when failed to generate tests for unmanaged folder

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java, src/controller/testController.ts, src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts
=> fix: Better handling the initialization error in JUnit4

CHANGELOG.md, java-extension/build-tools/pom.xml, java-extension/com.microsoft.java.test.plugin.site/category.xml, java-extension/com.microsoft.java.test.plugin.site/pom.xml, java-extension/com.microsoft.java.test.plugin/META-INF/MANIFEST.MF, java-extension/com.microsoft.java.test.plugin/pom.xml, java-extension/com.microsoft.java.test.runner/pom.xml, java-extension/pom.xml, package-lock.json, package.json
=> chore: Prepare for 0.34.1

src/extension.ts
=> fix: Make sure extension could be activated

CHANGELOG.md, java-extension/build-tools/pom.xml, java-extension/com.microsoft.java.test.plugin.site/category.xml, java-extension/com.microsoft.java.test.plugin.site/pom.xml, java-extension/com.microsoft.java.test.plugin/META-INF/MANIFEST.MF, java-extension/com.microsoft.java.test.plugin/pom.xml, java-extension/com.microsoft.java.test.runner/pom.xml, java-extension/pom.xml, package-lock.json, package.json
=> chore: Prepare for 0.34.2

package-lock.json, package.json, src/controller/debouncing.ts, src/extension.ts, src/utils/commandUtils.ts
=> chore: Bump dependencies version

scripts/prepare-nightly-build.js
pipeline is configured in classic way. engine is already 1.65
=> prepare for pre-release

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java, java-extension/com.microsoft.java.test.plugin/target.target
This fixes the Error 1 in https://github.com/microsoft/vscode-java-pack/issues/956
=> fix: add null check

src/controller/testController.ts
As suggested in https://github.com/microsoft/vscode-java-test/pull/1412#pullrequestreview-949352726 , selecting all invocations of a method for re-run does not lead to a "not supported error" anymore. Instead, the method is run normally:
resolve https://github.com/microsoft/vscode-java-test/issues/1416
=> no more error on all-invocations re-run

src/controller/testController.ts, src/extension.ts
=> fix: Adopt serverReady() API

.github/workflows/build.yml, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/launchers/JUnitLaunchConfigurationDelegate.java, java-extension/pom.xml
=> chore: Update to Java 17 in CI

CHANGELOG.md, java-extension/build-tools/pom.xml, java-extension/com.microsoft.java.test.plugin.site/category.xml, java-extension/com.microsoft.java.test.plugin.site/pom.xml, java-extension/com.microsoft.java.test.plugin/META-INF/MANIFEST.MF, java-extension/com.microsoft.java.test.plugin/pom.xml, java-extension/com.microsoft.java.test.runner/pom.xml, java-extension/pom.xml, package-lock.json, package.json
=> chore: Prepare for 0.35.1

CHANGELOG.md, java-extension/build-tools/pom.xml, java-extension/com.microsoft.java.test.plugin.site/category.xml, java-extension/com.microsoft.java.test.plugin.site/pom.xml, java-extension/com.microsoft.java.test.plugin/META-INF/MANIFEST.MF, java-extension/com.microsoft.java.test.plugin/pom.xml, java-extension/com.microsoft.java.test.runner/pom.xml, java-extension/pom.xml, package-lock.json, package.json
=> chore(deps): Bump vscode-extension-telemetry-wrapper to 0.13.1

src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts, test/suite/JUnitAnalyzer.test.ts
=> fix: Line separators are missing in diff messages

package-lock.json, package.json, src/controller/utils.ts, src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts
=> feat: Add codicon in the labels of test items

src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts, test/suite/JUnitAnalyzer.test.ts, test/suite/utils.ts
=> fix: Should remove description when display name is equal with label

java-extension/com.microsoft.java.test.plugin/target.target, java-extension/pom.xml, package-lock.json, package.json
=> chore: Update dependency versions

src/commands/testDependenciesCommands.ts
=> fix: Update the default value when enabling tests

src/controller/utils.ts
=> fix: Show test items in their declaration order

CHANGELOG.md, java-extension/build-tools/pom.xml, java-extension/com.microsoft.java.test.plugin.site/category.xml, java-extension/com.microsoft.java.test.plugin.site/pom.xml, java-extension/com.microsoft.java.test.plugin/META-INF/MANIFEST.MF, java-extension/com.microsoft.java.test.plugin/pom.xml, java-extension/com.microsoft.java.test.runner/pom.xml, java-extension/pom.xml, package-lock.json, package.json
=> chore: Prepare for 0.36.0

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/model/builder/JavaTestItemBuilder.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestItemUtils.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java
=> refactor: Use builder pattern to construct Java test items

ThirdPartyNotices.txt, package-lock.json, package.json, src/controller/testController.ts, src/controller/testTagStore.ts, src/controller/utils.ts, src/inversify.config.ts, tsconfig.json
- Change the id of test controller to 'java'.
- Change the runnable tag name to 'runnable'.
- Adopt InversifyJS to provide singleton support.
=> refactor: Rename the test controller and runnable tag

src/commands/navigation/navigationCommands.ts, src/references-view.d.ts
=> fix: Update the reference view extension id

package-lock.json, package.json, package.nls.json, package.nls.zh.json, src/runConfigs.ts, src/utils/launchUtils.ts, test/suite/launchUtils.test.ts
=> fix: Add 'testKind' to the test configuration

CHANGELOG.md, java-extension/build-tools/pom.xml, java-extension/com.microsoft.java.test.plugin.site/category.xml, java-extension/com.microsoft.java.test.plugin.site/pom.xml, java-extension/com.microsoft.java.test.plugin/META-INF/MANIFEST.MF, java-extension/com.microsoft.java.test.plugin/pom.xml, java-extension/com.microsoft.java.test.runner/pom.xml, java-extension/pom.xml, package-lock.json, package.json
=> chore: Prepare for 0.37.1

java-extension/com.microsoft.java.test.plugin/target.target, java-extension/pom.xml
=> chore: Update target platform links

java-extension/com.microsoft.java.test.plugin/.classpath, java-extension/com.microsoft.java.test.plugin/.project, java-extension/com.microsoft.java.test.plugin/.settings/org.eclipse.core.resources.prefs, java-extension/com.microsoft.java.test.plugin/.settings/org.eclipse.jdt.core.prefs, java-extension/com.microsoft.java.test.plugin/.settings/org.eclipse.m2e.core.prefs, java-extension/com.microsoft.java.test.plugin/target.target, java-extension/pom.xml, package.json
=> fix: Update the build configurations

package-lock.json, package.json, src/commands/testDependenciesCommands.ts
=> chore: Update dependencies

src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts, test/suite/JUnitAnalyzer.test.ts, test/test-projects/junit/pom.xml, test/test-projects/junit/src/test/java/junit5/VertxTest.java
fix https://github.com/microsoft/vscode-java-test/issues/1534
=> fix: Cannot run normal JUnit 5 test methods with multiple parameters

java-extension/com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/testng/TestNGListener.java, test/test-projects/old-testng/pom.xml, test/test-projects/old-testng/src/main/java/test/project/App.java, test/test-projects/old-testng/src/test/java/test/project/AppTest.java
=> Adding support for older testng versions

src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts, test/suite/JUnitAnalyzer.test.ts, test/test-projects/junit/src/test/java/junit5/TestFactoryTest.java
=> fix: Cannot run @TestFactory tests

package.json, package.nls.json, package.nls.zh.json, src/runConfigs.ts, src/utils/launchUtils.ts, test/suite/config.test.ts
=> feat: Support 'postDebugTask' in test configuration

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/launchers/JUnitLaunchUtils.java
=> fix: Set working directory to linked folder when it's unmanaged folder projects

.vscode/settings.json, ThirdPartyNotices.txt, java-extension/com.microsoft.java.test.plugin/META-INF/MANIFEST.MF, java-extension/com.microsoft.java.test.plugin/plugin.xml, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/coverage/CoverageHandler.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/coverage/model/BranchCoverage.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/coverage/model/LineCoverage.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/coverage/model/MethodCoverage.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/coverage/model/SourceFileCoverage.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/handler/TestDelegateCommandHandler.java, java-extension/com.microsoft.java.test.target/com.microsoft.java.test.tp.target, package-lock.json, package.json, package.nls.json, package.nls.zh.json, scripts/buildJdtlsExt.js, src/constants.ts, src/controller/testController.ts, src/provider/JavaTestCoverageProvider.ts, src/runConfigs.ts, src/types.ts, src/utils/coverageUtils.ts, src/utils/launchUtils.ts, vscode.proposed.testCoverage.d.ts
A video shows the experience.
https://github.com/microsoft/vscode-java-test/assets/6193897/a0e05045-ba67-496f-bd9e-841affab7aca
=> Implement the test coverage feature

java-extension/pom.xml
This addresses an issue with proxy settings described in microsoft/vscode-java-test#1656
=> upgrade tycho to v4.0.5

src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts, src/runners/testngRunner/TestNGRunnerResultAnalyzer.ts
=> fix: Enable html support for test outputs

java-extension/com.microsoft.java.test.plugin/META-INF/MANIFEST.MF, java-extension/com.microsoft.java.test.target/com.microsoft.java.test.tp.target, package.json, test/index.ts
=> fix: Bump org.jacoco.core to 8.12

scripts/buildJdtlsExt.js
=> build - Update jacoco to 0.8.12

java-extension/com.microsoft.java.test.plugin/META-INF/MANIFEST.MF, java-extension/com.microsoft.java.test.target/com.microsoft.java.test.tp.target, package.json
- Fixes #1759
- Supports ASM 9.8
CC'ing @jdneo
=> Update to Jacoco 0.8.13

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/ProjectTestUtils.java
Fixes #1782 
Test vsix - [Test Runner for Java 0.43.3](https://github.com/snjeza/vscode-test/raw/refs/heads/master/vscode-java-test-0.43.3.vsix)
=> Test Runner for Java doesn't recognize tests
