microsoft/vscode-java-test

extension/README.md, extension/package.json, extension/src/extension.ts, extension/src/utility.ts
when port is fixed, launching multiple cases sequentially.  might hit the bp of wrong test case
=> change fixed port to random port

extension/src/classPathManager.ts, extension/src/extension.ts, extension/src/fetchTestUtility.ts, extension/src/junitCodeLensProvider.ts, extension/src/protocols.ts, extension/src/testResourceManager.ts
use fspath rather than path as test storage cache's key because fspath would transform windows path to lower case;
fix a bug when resolving parent; and move the logic to fetchtestUtility.ts
=> fix some minor bugs

extension/src/extension.ts
To fix bug #66
if codelens is resolved and triggered running tests before test resource explorer loads all tests, the test result might be lost
=> wait for test resource manager to load all tests when activating the extension

extension/src/Explorer/testExplorer.ts
=> fix bug: test explorer class node's name is wrongly trimmed for default package case

extension/package.json, extension/src/testReportProvider.ts
currently , when user opens test report, test explorer would disappear. We might need combined conditions to determine when the explorer would show. However, seems vscode hasn't support complex condition for explorer view yet(opened an issue https://github.com/Microsoft/vscode/issues/43407 to track), so the fix still wouldn't work when user open 'pom.xml', but i think that is a rare case when user need the test explorer to be around.
=> walkaround: test explorer would disappear when user open test report

extension/src/classPathManager.ts, extension/src/projectManager.ts
scenario: user hasn't opened any folder and they trigger "edit test configuration" command, which would activate the extension. For this case, we need to check whether workspace  exists
=> check workspace before using it

extension/src/Constants/configs.ts, extension/src/Explorer/testExplorer.ts, extension/src/Models/testConfig.ts, extension/src/Runner/JarFileRunner/jarFileTestRunner.ts, extension/src/Runner/testRunner.ts, extension/src/Runner/testRunnerParameters.ts, extension/src/Runner/testRunnerWrapper.ts, extension/src/extension.ts, extension/src/testConfigManager.ts
1. add `default` section in test configuration. This way, user could specify the default config to pick when invoking "Run test".
2. rename test config file from "test-launch.json" to 'test.launch.json' as we changed the format of test configuration file and it isn't back-compatible
=> add default config

extension/src/Runner/JarFileRunner/jarFileTestRunner.ts, extension/src/Runner/testRunnerWrapper.ts, extension/src/testStatusBarProvider.ts
previous: if runner failed, e.g. cancel a test run, then the partial result won't be updated
current: always update test result even if it is partial
=> behavior change: always show test report and update test status even if runner failed

extension/package.json, extension/src/Constants/commands.ts, extension/src/Explorer/testExplorer.ts, extension/src/Utils/Logger/outputTransport.ts, extension/src/extension.ts, extension/src/testStatusBarProvider.ts
A better way to show cancel button on test explorer is it would replace original `Run test` button once a test run is started. Currently tree explorer icon couldn't be dynamically updated, so remove it to avoid confusing.
=> remove cancel test button from test explorer as it is a little bit confusing

extension/resources/templates/report.pug, extension/src/testReportProvider.ts
previous: show error report
now: error snippets are prepended in previous report so user could still view previous report before rerunning the test.
=> change report refresh behavior when test files are changed but the test hasn't been rerun

extension/package-lock.json, extension/src/Constants/configs.ts, extension/src/Utils/Logger/telemetryTransport.ts, extension/src/extension.ts, extension/src/testConfigManager.ts
#213 #230 
I still cannot repro this scenario, actions:
1. fix telemetry log issue, `meta` would be record as [object, object] string literal.
2. add more detailed error message.
3. add retry logic for disk write
4. change file write logic: reference [the recommended way to write file in node](https://nodejs.org/api/fs.html#fs_fs_access_path_mode_callback)
=> add retry logic for file create and add more details for error message

com.microsoft.java.test.runner/pom.xml, com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/CustomizedJUnitCoreRunner.java, com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/JUnitLauncher.java, com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/TestOutputSream.java, com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/TestReportItem.java, com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/TestReportType.java, com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/TestRunnerUtil.java, com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/TestStream.java, com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/TestingMessageHelper.java, com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/listeners/CustomizedJUnitTestListener.java
the errors/info generated by the junit runner would be in a format like below:
Length + serialized json string
=> rewrite junit runner to generate unified output/error

pom.xml
e.g. org.eclipse.jdt.core.IClasspathEntry.isTest is only available since 3.14.0, while oxygen's version is 3.13.0
=> use photon because some API of org.eclipse.jdt.core is only available since 3.14.0

extension/src/Constants/commands.ts, extension/src/Explorer/testExplorer.ts, extension/src/Explorer/testTreeNode.ts, extension/src/Models/protocols.ts, extension/src/Utils/fetchTestUtility.ts, extension/src/testResourceManager.ts
This PR is to reimplement the Test explorer: using lazy load strategy. #259 
GIF: 
Future tasks:
- Currently, we wrap the `TestSuite` into the `SearchResult`, we should consider simplifying the protocol in the future.
=> Implement test explorer lazyload - TypeScript part

extension/src/extension.ts, extension/src/testResultManager.ts
The test result manager is used to store the test result. It will be consumed by the test report.
The data structure is
`fsPath` -> `IResultsInFsPath`: all the results in this fsPath.
`IResultsInFsPath` is a map, the key is all the methods name.
`methodName` -> results of this method
=> Add test result manager

com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/model/SearchTestItemParams.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java, extension/src/explorer/testExplorer.ts, extension/src/protocols.ts, extension/src/utils/commandUtils.ts, extension/src/utils/protocolUtils.ts
Rename the `XXXXRequest` to `XXXXParams` to make the name for suitable
=> Rename request to params

com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/testng/TestNGRunner.java
Fix #416 
Reference: https://stackoverflow.com/a/38245000
=> Disable generating the test-output folder when running TestNG tests

com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/TestNGTestSearcher.java, extension/src/runners/runnerExecutor.ts
Fix #407 
TestNG test method does not restrict that it must have the public signature.
=> Fix the bug that cannot find out TestNG test items which do not have public signature

extension/src/protocols.ts, extension/src/testConfigManager.ts
Since it's returned from LS, the type should be string.
Fix #431
=> Fix the bug that workingDirectory is not generated in launch.test.json

com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/JUnit4TestSearcher.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/JUnit5TestSearcher.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/TestNGTestSearcher.java, com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java
This PR reads JUnit 5's `@DisplayName` annotation and shows it in the side bar instead of the method names:
=> Support for JUnit 5's DisplayName

src/extension.ts
=> Resolve the warning: uses a document selector without scheme

resources/templates/report.pug, resources/templates/report_method_table.pug, resources/templates/scss/report.scss, src/protocols.ts, src/runners/baseRunner/BaseRunnerResultAnalyzer.ts, src/runners/testngRunner/TestNGRunnerResultAnalyzer.ts, src/testReportProvider.ts
=> Show display name in the test report

java-extension/com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/common/TestOutputStream.java, src/runners/baseRunner/BaseRunner.ts
This is the first part of the work for issue #505
=> Stop clipping the EOL when parsing the runner output

package.json, package.nls.json, package.nls.zh.json, src/commands/executeTests.ts, src/commands/explorerCommands.ts, src/constants/configs.ts, src/constants/dialogOptions.ts, src/extension.ts, src/runConfigs.ts, src/runners/runnerExecutor.ts, src/testConfigManager.ts, src/utils/configUtils.ts
related to #524 
1. Remove the command: run/debug with configuration
2. Add a built-in configuration: {: "${workspaceFolder}"}
3. Set default configuration into a setting
=> Support to set the default configuration name

src/runners/baseRunner/BaseRunner.ts, src/runners/runnerExecutor.ts
=> Get the project name from the test item itself instead of reading the config file

java-extension/com.microsoft.java.test.runner/pom.xml, java-extension/com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/junit5/CustomizedConsoleLauncher.java
The `JOptSimpleCommandLineOptionsParser` is replaced by `PicocliCommandLineOptionsParser` in JUnit 5.
Using `JOptSimpleCommandLineOptionsParser` may not able to parse the argument correctly, thus causing some the test cases are skipped.
=> Upgrade JUnit5 to 1.3.2

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/ProjectUtils.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/RuntimeClassPathUtils.java
To address #534 & #621 
The root cause is that the `application.properties` in `src` is loaded before that in `test`
The `target/test-class` must come before `target/class`.
=> [bugfix] Put the target/test-class before target/class when calculating the classpath

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/RuntimeClassPathUtils.java, src/utils/commandUtils.ts
Fix the regression in #629 
We should use `List` instead of `Set` since `Set` has no order
=> Fix a regression when calculate the classpath

src/codeLensProvider.ts, src/runners/baseRunner/BaseRunnerResultAnalyzer.ts
Get the searching result from the language server, then for each item in the searching result, get the final result from the cache.
Directly show the result in the cache, which aligns with the output of the Test Runner.
=> Directly fetch the result from result cache

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/handler/TestDelegateCommandHandler.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/ProjectInfoFetcher.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/ProjectTestUtils.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/RuntimeClassPathUtils.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java, package.json, package.nls.json, package.nls.zh.json, src/commands/testPathCommands.ts, src/constants/commands.ts, src/extension.ts, src/testFileWatcher.ts, src/testResultManager.ts, src/utils/commandUtils.ts
=> feat: Add a command to list current test source paths

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java
=> fix: Filter out the default project when searching the test cases

src/constants/commands.ts, src/runners/runnerExecutor.ts, src/utils/commandUtils.ts
Resolve #669 
This change refers to the [PR](https://github.com/microsoft/vscode-java-debug/pull/561) in VS Code Java Debugger
=> feat: Automatically add --enable-preview to vmargs when necessary

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/BaseFrameworkSearcher.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/JUnit4TestSearcher.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/JUnit5TestSearcher.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/TestNGTestSearcher.java, src/runners/junit5Runner/JUnit5RunnerResultAnalyzer.ts
Resolve #644 
This change overrides the `isTestMethod()` in the child class. It's because different test frameworks have different restrictions about the method signature. And it's hard to differentiate them in just one method.
=> feat: Support @TestFactory in JUnit 5

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/model/TestLevel.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/BaseFrameworkSearcher.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestItemUtils.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java, src/codeLensProvider.ts, src/explorer/testExplorer.ts, src/protocols.ts, src/runners/junit5Runner/JUnit5Runner.ts
There is no need to differentiate `Class` and `Nested Class`
Since most of the resolving logic is the same.
=> refactor: Remove the Test Level: NESTED_CLASS

src/testReportProvider.ts
Fix #727
If the report is already opened, just update it instead of changing its position.
=> fix: Test report will just update instead of changing the column if it's already opened

src/runners/junit5Runner/JUnit5Runner.ts
=> fix: Remove class name restriction for JUnit 5

src/runConfigs.ts, src/utils/configUtils.ts
=> fix: Always assign a new object for the built-in configuration

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java, src/runners/baseRunner/BaseRunner.ts, src/runners/junit5Runner/JUnit5Runner.ts, src/testResultManager.ts, src/utils/protocolUtils.ts
Fix #42
> Note: The change `'.*'` -> `"'.*'"` is to fix a regression involved in #730
=> fix: Clear the results before running tests

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestItemUtils.java
=> fix: When expanding the explorer, got the error: Property must not be null: range

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/BaseFrameworkSearcher.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/JUnit4TestSearcher.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/JUnit5TestSearcher.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/TestNGTestSearcher.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestFrameworkUtils.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java
resolve #737 
By searching the annotation hierarchy, we can resolve the meta-annotation scenario.
=> feat: Support Junit 5 meta-annotations and composed annotations

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestFrameworkUtils.java
This is a regression issue introduced when supporting the meta-annotation.
=> fix: Cannot find the class which annotated with @Runwith

java-extension/com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/junit4/JUnit4ExecutionListener.java
Fix: #772 
Sometime the method name might be null, e.g. `@Runwith(JUnitPlatform.class)`.
Since it's just notifying the test engine (not a method) is started, we can skip it.
=> fix: Add null check for methodName in JUnit 4

package.json, package.nls.json, package.nls.zh.json
Related with #793 
Change the explorer name to Java.
- Since the `test` is a dependent panel and all languages can register their test explorers in there. So we should name it to specific `Java` instead  of general `test explorer`
=> fix: Change the explorer name and the activation event

src/commands/explorerCommands.ts, src/runners/ITestRunner.ts, src/runners/junit4Runner/Junit4Runner.ts, src/runners/runnerScheduler.ts, src/utils/launchUtils.ts, src/utils/protocolUtils.ts
The original API accepts the `ISearchTestItemParams`. While, the new API accepts `TestTreeNode` instead. Which is easier to know that the task is triggered from Test Explorer or not.
=> refactor: Change to API of scheduler

src/runners/runnerScheduler.ts, src/utils/configUtils.ts
The previous implementation will get the config and resolve the variables in another call.
=> refactor: Directly get the resolved configuration

package.json, package.nls.json, package.nls.zh.json, src/constants/configs.ts, src/runners/runnerScheduler.ts, src/utils/settingUtils.ts
We don't need this setting any more because we are fully leverage the debugger to launch the tests now.
=> Deprecate the setting 'java.test.forceBuildBeforeLaunchTest'

src/commands/explorerCommands.ts, src/constants/commands.ts
The previous implementation will return `[]` on cancel. Cause the output channel having:
both `Test job is canceled.` & `'No test items found.'` when the user click cancel.
=> Better handling the cancel event

CHANGELOG.md, package.json, package.nls.json, package.nls.zh.json, src/constants/configs.ts, src/runners/runnerScheduler.ts, src/utils/settingUtils.ts
=> Remove the setting 'java.test.saveAllBeforeLaunchTest'

src/utils/launchUtils.ts
fix #865 
Since the `process.env` will be automatically added to the launch configuration
=> fix: Stop passing the env in process to the launch config

src/runners/runnerScheduler.ts, src/utils/configUtils.ts, src/utils/settingUtils.ts
The reason to remove the resolving logic is that we now fully leverage the Java debugger to launch the tests. Thus the Java debugger will help resolving those variables.
=> refactor: Stop resolving the variables in launch configuration

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/launchers/JUnitLaunchConfiguration.java
fix #872 
The GradleClasspathProvider could not handle the modular project well. Just use the default classpath provider to resolve the classpath and modulepath.
=> Use StandardClasspathProvider to resolve classpath for Gradle project

src/utils/launchUtils.ts
Instead of guessing the encoding. Users should provide the encoding settings by their own through the `vmargs` in `java.test.config`
=> Remove the encoding guess logic

gulpfile.js
This PR is to simplify the build process.
Both the checkstyle check and the jar build task can be combined into one `mvn verify` call. There is no need to separate them.
=> chore: Speed up the build process

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java, src/runners/runnerScheduler.ts
This PR provide following changes:
- fix typo: `Unkonwn`
- Set test kind field when creating new class level test item
- Return list from hashmap instead of maintaining a separate list
=> bugfix: Apply the test kind for class level test items

src/commands/explorerCommands.ts, src/commands/runFromCodeLens.ts, src/runners/models.ts, src/runners/runnerScheduler.ts, src/testItemModel.ts, src/utils/launchUtils.ts, src/utils/protocolUtils.ts
fix #911 
By fixing this bug, also did some refactoring work that save the required information in the `runnerContext`, which is to avoid passing the `test items` deeper in the function calls.
=> bugfix: Cannot trigger test from explorer

src/explorer/testExplorer.ts, src/testFileWatcher.ts, src/testItemModel.ts, src/testResultManager.ts
This PR does the following two things:
1. Move the `fsPathToNodeMapping` from explorer to `testItemModel`. Since the model layer should be the place to cache the testItems.
2. When saving the test items, always return the object reference instead a new object. This is for incremental update purpose of the test explorer
=> refactor: Move the test item node cache from explorer to model layer

resources/templates/report_method_table.pug, resources/templates/scss/report.scss
fix #939
fix #938
fix #933
This PR include the following change
- Wrap the word for the stacktrace area
- Add ellipsis style to The class and method name
- Change the time format from `ms` to `s`
=> fix: Improve the test report style

src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts, test/maven-junit4-suite/codelens.test.ts, test/shared.ts, test/test-projects/junit4/src/test/java/junit4/AssumeTest.java
=> Fix the regression bug: assume failure is not marked as skipped

resources/templates/report_method_table.pug, resources/templates/scss/report.scss
=> Highlight 'Caused by' in the stack trace

src/runners/runnerScheduler.ts
=> bugfix: Do not show test report when there is no test results

package.json, src/constants/commands.ts, src/explorer/testExplorer.ts, src/extension.ts, src/testFileWatcher.ts
=> feat: Adopt the Java Language Server's new API

.vscode/launch.json, java-extension/com.microsoft.java.test.plugin/META-INF/MANIFEST.MF, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/BaseFrameworkSearcher.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/JUnit4TestSearcher.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/JUnit5TestSearcher.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/TestFrameworkSearcher.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/TestNGTestSearcher.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestFrameworkUtils.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java, java-extension/com.microsoft.java.test.plugin/target.target, java-extension/pom.xml, package-lock.json, test/gradle-junit5-suite/codelens.test.ts, test/shared.ts, test/test-projects/junit5/src/test/java/junit5/FastTest.java, test/test-projects/junit5/src/test/java/junit5/MetaAnnotationTest.java
fix #1039 
Using the attached source file in #1039, below are some data points with this PR change:
| | 1 | 2 | 3 | 4 | 5 | AVG |
|---|---|---|---|---|---|---|
| New | 1432 | 2262 | 1036 | 2186 | 1214 | 1626 |
| Old | 8257 | 8380 | 13953 | 8678 | 10782 | 10010 |
| | 1 | 2 | 3 | 4 | 5 | AVG |
|---|---|---|---|---|---|---|
| New | 380 | 284 | 278 | 258 | 274 | 295 |
| Old | 2963 | 3383 | 3122 | 2659 | 2635 | 2952 |
| | 1 | 2 | 3 | 4 | 5 | AVG |
|---|---|---|---|---|---|---|
| New | 2110 | 3438 | 1966 | 2387 | 2375 | 2455 |
| Old | 10714 | 8551 | 9146 | 9828 | 11441 | 9936 |
| | 1 | 2 | 3 | 4 | 5 | AVG |
|---|---|---|---|---|---|---|
| New | 1760 | 395 | 345 | 436 | 405 | 668 |
| Old | 4597 | 4041 | 3863 | 3586 | 3584 | 3934 |
Besides this PR change, we can improve the perf further, …
=> Improve the perf when resolving code lens in large java file

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/launchers/JUnitLaunchUtils.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/model/TestItem.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/JUnit5TestSearcher.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestItemUtils.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java, src/commands/explorerCommands.ts, src/commands/runFromCodeLens.ts, src/explorer/testExplorer.ts, src/protocols.ts, src/runners/models.ts, src/utils/commandUtils.ts, src/utils/launchUtils.ts, test/gradle-junit5-suite/codelens.test.ts
Only resolve the method parameter types when needed. Before this change, we will always parse the method parameters when it's a JUnit 5's case. But that's not necessary because this information is only needed when the user wants to launch at method level.
=> refactor: Lazy load the parameter types

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java, test/test-projects/modular-gradle/build.gradle
Did some profiling to check the improvement. Given a 5000+ lines test file, doing the following operations:
- 5 times of code completion (keep enter `.` and `backspace`)
- write `String a = "";`
- write `String b = a;`
- insert code snippet `systrace`.
=> Get ASTNode from ASTProvider

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/launchers/JUnitLaunchUtils.java, test/gradle-junit5-suite/codelens.test.ts, test/test-projects/junit5/src/test/java/junit5/ParameterizedAnnotationTest.java
=> bugfix: Cannot run parameterized test if the parameter has generic types

java-extension/com.microsoft.java.test.plugin/META-INF/MANIFEST.MF
=> chore: Set bundle required environment to JavaSE-1.8

package.json, package.nls.json, package.nls.zh.json, src/runConfigs.ts, src/utils/launchUtils.ts
Address #852 
Use `vmArgs` to align with the debug launch configuration.
The `vmargs` is deprecated
=> Use vmArgs in test configuration setting

package.json, package.nls.json, package.nls.zh.json, src/commands/runFromUri.ts, src/constants/commands.ts, src/extension.ts, src/testItemModel.ts, src/utils/commandUtils.ts, test/gradle-junit5-suite/index.ts, test/gradle-junit5-suite/runFromEditor.test.ts
Add a new command to support run tests in current active file.
Part of #531
=> feat: Support run tests from current file

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/launchers/JUnitLaunchConfigurationDelegate.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/launchers/JUnitLaunchUtils.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/model/SearchTestItemParams.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java, package.json, package.nls.json, package.nls.zh.json, src/commands/explorerCommands.ts, src/constants/commands.ts, src/extension.ts, src/protocols.ts, src/runners/models.ts, src/testItemModel.ts, src/utils/commandUtils.ts, src/utils/launchUtils.ts
Support run tests from the Java Project explorer
https://user-images.githubusercontent.com/6193897/104272416-05afab80-54d8-11eb-9542-03ff98789c5b.mp4
Since we need to run all the children nodes if the explorer is in Hierarchical mode, so I made some workaround in the implementation. Basically it's to patch the arguments resolved by the configuration delegator.
=> feat: Support running tests from Java Project explorer

package-lock.json, package.json, src/commands/explorerCommands.ts, src/commands/testReportCommands.ts, src/constants/commands.ts, src/explorer/testExplorer.ts, src/extension.ts, src/utils/configUtils.ts
This PR contains following changes:
- Use the VS Code built-in `open` command for the tree nodes in the test explorer
- Since using the built-in command will lose the BI, using a event counter to track the ui operations
- Better treat with the focus when opening documents from the test report.
Related with #1128
=> fix: Improve the accessibility of opening document

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/launchers/JUnitLaunchUtils.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/model/TestItem.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/BaseFrameworkSearcher.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/JUnit4TestSearcher.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/JUnit5TestSearcher.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/TestFrameworkSearcher.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/searcher/TestNGTestSearcher.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestFrameworkUtils.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestItemUtils.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java
This PR leverage the upstream Test Finder for test discovery.
The previous implementation used `SearchEngine`, since it's not good at handleing meta annotation, some bugs are introduced.
fix #641
fix #773
fix #818
=> refactor: Leverage test finder for test discovery

src/commands/testReportCommands.ts
=> fix: Cannot navigate to source for JUnit4 parameterized tests

package.json, package.nls.json, package.nls.zh.json
Address https://github.com/microsoft/vscode-java-pack/issues/540
=> feat: Add welcome view when no folder opened

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestGenerationUtils.java
Fix a regression.
The JUnit 4 & 5's BeforeClass and AfterClass method should be static.
=> fix: Add static modifier for Junit 4 & 5's Before/AfterClass methods

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/model/Option.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/JUnitPlugin.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestGenerationUtils.java, src/commands/generationCommands.ts
=> fix: Display more friendly options when generating tests

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestGenerationUtils.java
=> fix: Catch the exception when package fragment does not exist

src/runners/baseRunner/BaseRunner.ts, src/utils/launchUtils.ts
We use the launch configuration name to identify if a debug session is end and to do the clean up work.
Previously, since the launch configuration name is staticly same, that causes the test sessions cannot be queued. (All the session names are same)
=> fix: Can queue the running tests

src/commands/testExplorerCommands.ts
Previously in the proposed API, the root item still have an implicit parent. But in the stable release, the implicit parent is removed and become undefined.
So in the while check, we can just check the item itself.
=> fix: Cannot run PDE tests

gulpfile.js, src/extension.ts
fix #1269
Should call JLS only when its ready
=> fix: Failed to create test item when test controller is not initialized

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/launchers/JUnitLaunchConfiguration.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/launchers/JUnitLaunchConfigurationTemplate.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/launchers/JUnitLaunchUtils.java
fix #1273 
Simply pass a `mainType` to the launch configuration to let upstream resolve the classpath/modulepath quickly.
Before this change, we just set the container, which will invoke a lot of computation on type hierarchy
=> fix: Performance regression when resolving launch arguments

src/constants.ts, src/extension.ts
`testing.refreshTests` has been removed in VS Code so we need to use the extension customized one
fix #1298
=> fix: Use the customized refresh test explorer command

src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts
fix #1296 
Now when running JUnit4's parameterized tests, the appearance is like what it is in Eclipse:
=> ux: Improve the experience showing the JUnit4's parameterized tests

.github/workflows/build.yml, .vscode/launch.json, package.json, package.nls.json, package.nls.zh.json, src/runConfigs.ts, src/utils/launchUtils.ts, test/index.ts, test/suite/JUnitAnalyzer.test.ts, test/suite/config.test.ts, test/suite/utils.ts
=> feat: Add 'envFile' in test configuration

src/runners/testngRunner/TestNGRunnerResultAnalyzer.ts
=> fix: Support html markdown for TestNG output

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/model/Option.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestGenerationUtils.java
=> fix: Select @Test method by default when generating tests

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/model/JavaTestItem.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestItemUtils.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java, package.json, package.nls.json, package.nls.zh.json, src/commands/testDependenciesCommands.ts, src/constants.ts, src/controller/utils.ts, src/extension.ts, src/types.ts
This PR fixes #1344. 
We will help users to download test dependencies and setup their projects. (when its a unmanaged folder)
=> feat: Support enabling tests for unmanaged folder

src/commands/testDependenciesCommands.ts
Starts from TestNG 7.x requires lsf4j.
Meanwhile, this PR dedup the referenced libraries setting when updating it.
=> fix: Should setup TestNG correctly

CHANGELOG.md, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java
fix #1364.
According to the API document, `CompilationUnit.findDeclaringNode()` will return null when:
- if the corresponding node cannot be determined.
- if bindings were not requested when this AST was built.
While `ASTNodeSearchUtil` works in this case.
> Note: there are other usages for `CompilationUnit.findDeclaringNode()`, will consider if they should also be replaced to `ASTNodeSearchUtil`.
=> fix: Should recognize test classes with '$' in their names

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestGenerationUtils.java, package-lock.json, package.json
- The upstream runner could not fine tests when '$' is in class name,
so we use '_' when generating test classes.
// see discussion in #1367
=> fix: Generate '_' instead of '$' for inner class

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestSearchUtils.java, src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts, test/suite/navigation.test.ts, test/test-projects/junit/src/test/java/junit4/BaseTest.java, test/test-projects/junit/src/test/java/junit4/ExtendedTest.java
- When append test messages, keep finding the test method from current type to all of its supertype.
=> fix: Find the location of inherited test methods

package-lock.json, package.json, package.nls.json, package.nls.zh.json, src/controller/testController.ts
resolve: #1348 
Now the refresh button will appear at navigation bar
=> feat: Adopt VS Code's refresh tests API

package.json, package.nls.json, package.nls.zh.json, src/commands/testExplorerCommands.ts, src/constants.ts, src/controller/testController.ts, src/extension.ts
follow-up of #1384 
- since the platform already registered the command in palette,
the existing one from Java side can be removed.
https://user-images.githubusercontent.com/6193897/156951398-46c7feca-1bc6-4302-871a-c57eddddc8a6.mp4
=> fix: Remove the refresh Java tests command

src/runners/baseRunner/RunnerResultAnalyzer.ts, src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts, src/runners/testngRunner/TestNGRunnerResultAnalyzer.ts
- Simplify the stacktrace by excluding internal traces, which defined in
getStacktraceFilter().
fix #1281
=> feat: Simplify the stacktrace

src/runners/baseRunner/RunnerResultAnalyzer.ts, test/suite/JUnitAnalyzer.test.ts, test/suite/config.test.ts, test/suite/utils.ts
fix #1392
The test message should always display inside the range of a test message. Even when its stacktrace locates outside of it. In this case, we simply set the test message location at the first line of the test case.
=> fix: Always display the test message in the test's range

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/launchers/JUnitLaunchConfigurationDelegate.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/launchers/JUnitLaunchUtils.java, src/controller/testController.ts, src/controller/testItemDataCache.ts, src/controller/utils.ts, src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts, src/types.ts, src/utils/launchUtils.ts
Support for re-running/debugging a parameterized JUnit5 test with a single set of parameters, similar to the corresponding eclipse feature:
resolve https://github.com/microsoft/vscode-java-test/issues/1408
=> feat: re-run single JUnit5 parameterized test invocation via uniqueId

src/controller/testController.ts
Only run class instead of methods if no method is restricted to a single invocation.
The example from the issue may now be debugged as expected (no more execution of all parameter-sets):
resolve https://github.com/microsoft/vscode-java-test/issues/1411
=> fix: re-run invocations from all methods in class

src/runners/baseRunner/RunnerResultAnalyzer.ts
The range in vscode is 0-based, which the position in stacktrace is 1-based.
=> fix: The item line number does not match the one in stacktrace

src/controller/testController.ts, test/suite/testController.handleInvocations.test.ts
The part of the `testController` which handles the preparation for re-running single invocations of parameterized methods was not tested, as discussed in https://github.com/microsoft/vscode-java-test/pull/1417#pullrequestreview-958553125
=> add some unit-tests for invocations re-run

java-extension/com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/testng/TestNGListener.java
TestNG version prior to like 6.7.x didn't failed the test method when
related configuration method failed. Instead they skipped all the
test methods which results in no error message in the Test Explorer.
This change add those missing information if the test method is skipped
followed by a configuration method failure.
=> add proper error reporting for old testng

src/controller/utils.ts, src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts, src/types.ts
Fixed how parameterized test methods are sorted to ensure that they use a natural sort.
=> Fixed how parameterized test methods are sorted

src/runners/baseRunner/RunnerResultAnalyzer.ts, src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts, src/runners/testngRunner/TestNGRunnerResultAnalyzer.ts, test/suite/JUnitAnalyzer.test.ts, test/test-projects/junit/src/test/java/junit5/TestWithExtractedEqualityAssertion.java
resolves https://github.com/microsoft/vscode-java-test/issues/1522
=> deduplicate diff test messages

java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/launchers/JUnitLaunchConfigurationDelegate.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/launchers/JUnitLaunchUtils.java, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/model/Response.java, src/controller/testController.ts, src/runners/baseRunner/BaseRunner.ts, src/utils/launchUtils.ts, test/suite/launchUtils.test.ts
=> fix: Stop the test session when exception happens

package.json, src/commands/projectExplorerCommands.ts
fix #1574 
Here using a negative lookahead to eliminate `resource` node, this is better than the previous approach.
=> fix: Cannot run tests from Java Projects view

.eslintrc.js, package.json, package.nls.json, src/controller/testController.ts, src/runConfigs.ts, src/utils/launchUtils.ts, test/suite/config.test.ts
This PR adds support for specifying a different JRE (by providing the java executable) to be used for running the test. This helps when some tests needs to be executed against a different java version to
- Make sure certain application components are future proof.
- Debug issues which has raised when application was running with a newer java version, Which a test is used to reproduce that error.
- etc.
=> Add support to specify java executable to use for test

.gitignore, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/ProjectTestUtils.java
=> fix: NPE when get test source paths

src/constants.ts, src/controller/testController.ts, src/controller/utils.ts, src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts, test/suite/JUnitAnalyzer.test.ts, test/suite/testController.handleInvocations.test.ts, test/test-projects/junit/src/test/java/junit5/TestFactoryTest.java
- Store the test data for the test invocations as well.
- Remove the logic that adding prefix to the invocations. Instead,
- Using the information returned from the runner to compose the ids.
fix #1617
=> fix: JUnit5 DynamicContainer are not working

java-extension/com.microsoft.java.test.target/com.microsoft.java.test.tp.target
The version of JDT.LS is fixed to prevent update junit to 5.10.x. See: https://github.com/microsoft/vscode-java-test/pull/1608#issue-1904190398 for the reason.
fix #1633
=> build: Update target platform

README.md
The minimum JDK dependency may have reached 17 now
> org/eclipse/tycho/p2maven/repository/EclipsePluginArtifactHandler has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
=> docs: Update JDK to 17

extension.bundle.ts, java-extension/com.microsoft.java.test.plugin/src/main/java/com/microsoft/java/test/plugin/util/TestItemUtils.java, java-extension/com.microsoft.java.test.runner/src/main/java/com/microsoft/java/test/runner/testng/TestNGListener.java, src/runners/junitRunner/JUnitRunnerResultAnalyzer.ts, test/suite/JUnitAnalyzer.test.ts
Since test id returned from both the eclipse test runner and gradle test runner contain space between the param list. The previous logic to remove all spaces is redundant.
=> refactor - Remove the logic of eliminating spaces in param list

src/runners/baseRunner/RunnerResultAnalyzer.ts, src/runners/utils.ts
This is a common logic that can be reused by the gradle test runner
=> refactor - Extract the stacktrace parsing to util
